name: hyb-zone
channels:
-   conda-forge
-   bioconda
-   base
-   R
dependencies:
-   snakemake-minimal =7.32.3
-   samtools =1.17
-   bcftools=1.17
-   r-base=4.3.3
-   r-tidyverse=2.0.0
-   vcftools=0.1.16