name: hyb-zone
channels:
-   conda-forge
-   bioconda
-   base
-   R
dependencies:
-   snakemake-minimal =7.32.3
-   samtools =1.17
-   bcftools=1.17
-   r-base=4.3.1
-   r-ggplot2=3.4.3
-   r-gplots=3.1.3
-   r-gsalib=2.2.1
-   r-reshape=0.8.9
-   bioconductor-variantannotation=1.48.1
-   bioconductor-snpstats=1.52.0
-   vcftools=0.1.16